### PR TITLE
Remove "(Beta)" label and replace spaces with tabs

### PR DESCRIPTION
**Pull request by Kucharssim**
See https://pml-uva.slack.com/archives/G01PBL2S1MZ/p1655065737127509

### CODE REVIEW

**Review by shun2wang — COMMENTED** [review]
i think 'Beta' label should also be removed from translations in .po file, but  not sure if this is supposed to do it by developers or wait for the translator to remove it. (I'm afraid the translator will have difficulty detecting this change) . @boutinb what do you think.

**Comment by boutinb** [comment]
> i think 'Beta' label should also be removed from translations in .po file, but not sure if this is supposed to do it by developers or wait for the translator to remove it. (I'm afraid the translator will have difficulty detecting this change) . @boutinb what do you think.

That's a good point: it's better to remove directly in the po file the beta string in the translation: if not the translation will be removed.

**Review by vandenman — APPROVED** [review]
Changes are fine once you also adjust the .po files.

**Comment by boutinb** [comment]
Just talked with Simon: as the "Prophet" string is already a translated string, the po files do not have to be changed. The pot file will be automatically generated.

**Pull request merged**
